# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeaveAi < Formula
  desc "Weave AI CLI"
  homepage "https://weave.works"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.7.0/weave-ai_0.7.0_darwin_arm64.tar.gz"
      sha256 "72a70bd5db51ec64aaf43cd390184c08c47c0fdbe9610c60efec8d1f86f3cc25"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.7.0/weave-ai_0.7.0_darwin_amd64.tar.gz"
      sha256 "33e479043a1001a660ab404f6162f04824c97f1cb3dbe71f7ca02552d37f5487"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.7.0/weave-ai_0.7.0_linux_arm64.tar.gz"
      sha256 "feb84ec22183ecf9b453764680323f5f41a2b1d3257a1a6ca15ed1c7222f85aa"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.7.0/weave-ai_0.7.0_linux_amd64.tar.gz"
      sha256 "cd9ecacd89bb3bec39469913365438613e7ef2ae8f96984af88f6cbe03571ff2"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
  end

  test do
    system "#{bin}/weave-ai --version"
  end
end
