# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeaveAi < Formula
  desc "Weave AI CLI"
  homepage "https://weave.works"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.9.0/weave-ai_0.9.0_darwin_amd64.tar.gz"
      sha256 "6c189775417ef631ce742465ca765c2eb0318bd8d6b82f89c5bf148dce8710b4"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.9.0/weave-ai_0.9.0_darwin_arm64.tar.gz"
      sha256 "2e432d77e0f48c3544ce7963e11f69722b0b0062c1233aefc003cbe62618db48"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.9.0/weave-ai_0.9.0_linux_arm64.tar.gz"
      sha256 "c217b1e7aa2e56c5432c5861249ed722c19c73f683ec852ac74cb699d5921ffa"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.9.0/weave-ai_0.9.0_linux_amd64.tar.gz"
      sha256 "475367464e5b5d3b97edd3557f9708124d6d074c67d4be4e3cc2a13cf78c18fb"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
  end

  test do
    system "#{bin}/weave-ai --version"
  end
end
