# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WeaveAi < Formula
  desc "Weave AI CLI"
  homepage "https://weave.works"
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.8.1/weave-ai_0.8.1_darwin_amd64.tar.gz"
      sha256 "ae4a2b0b72c7f54ae36391f8e60902ce3092eee64c6d63683dfa48293b078eb5"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.8.1/weave-ai_0.8.1_darwin_arm64.tar.gz"
      sha256 "b6582fa8dce7c49fb62b9ff71e74b1760c3ea90abe77eebff1919fee58035e64"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.8.1/weave-ai_0.8.1_linux_arm64.tar.gz"
      sha256 "e0e866bd8bd54550aeb48a3a18545728dc317e1c9a5627f7563ab0509ade3416"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/weave-ai/weave-ai/releases/download/v0.8.1/weave-ai_0.8.1_linux_amd64.tar.gz"
      sha256 "19d76a1db406210df30065e80224a05589770fa6be6dea0bfd2d7fcaf0e8f370"

      def install
        bin.install "weave-ai"

        generate_completions_from_executable(bin/"weave-ai", "completion")
      end
    end
  end

  test do
    system "#{bin}/weave-ai --version"
  end
end
